"""complete control center data model

Revision ID: 202607300008
Revises: 202607290007
Create Date: 2026-07-30 10:31:19.317252
"""

from uuid import UUID

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "202607300008"
down_revision = "202607290007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_definitions",
        sa.Column("iso_code", sa.String(length=8), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("default_currency_code", sa.String(length=16), nullable=True),
        sa.Column("default_time_zone", sa.String(length=80), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("short_label", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_geo_definitions_display_name"), "geo_definitions", ["display_name"], unique=False)
    op.create_index(op.f("ix_geo_definitions_is_active"), "geo_definitions", ["is_active"], unique=False)
    op.create_index(op.f("ix_geo_definitions_iso_code"), "geo_definitions", ["iso_code"], unique=True)
    geo_table = sa.table(
        "geo_definitions",
        sa.column("id", sa.Uuid()),
        sa.column("iso_code", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("default_currency_code", sa.String()),
        sa.column("default_time_zone", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("color", sa.String()),
        sa.column("short_label", sa.String()),
    )
    op.bulk_insert(
        geo_table,
        [
            {
                "id": UUID("10000000-0000-4000-8000-000000000001"),
                "iso_code": "IN",
                "display_name": "Индия",
                "default_currency_code": "INR",
                "default_time_zone": "Asia/Kolkata",
                "is_active": True,
                "color": "#2563eb",
                "short_label": "IN",
            },
            {
                "id": UUID("10000000-0000-4000-8000-000000000002"),
                "iso_code": "KE",
                "display_name": "Кения",
                "default_currency_code": "KES",
                "default_time_zone": "Africa/Nairobi",
                "is_active": True,
                "color": "#059669",
                "short_label": "KE",
            },
            {
                "id": UUID("10000000-0000-4000-8000-000000000003"),
                "iso_code": "ZA",
                "display_name": "Южная Африка",
                "default_currency_code": "ZAR",
                "default_time_zone": "Africa/Johannesburg",
                "is_active": True,
                "color": "#d97706",
                "short_label": "ZA",
            },
            {
                "id": UUID("10000000-0000-4000-8000-000000000004"),
                "iso_code": "US",
                "display_name": "США",
                "default_currency_code": "USD",
                "default_time_zone": "America/New_York",
                "is_active": True,
                "color": "#7c3aed",
                "short_label": "US",
            },
        ],
    )
    op.create_table(
        "account_manager_history",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("previous_mcc_id", sa.Uuid(), nullable=True),
        sa.Column("current_mcc_id", sa.Uuid(), nullable=True),
        sa.Column("previous_manager_customer_id", sa.String(length=32), nullable=True),
        sa.Column("current_manager_customer_id", sa.String(length=32), nullable=True),
        sa.Column("previous_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=60), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=180), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["current_mcc_id"],
            ["mcc_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_mcc_id"],
            ["mcc_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_manager_history_account_id"), "account_manager_history", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_manager_history_changed_at"), "account_manager_history", ["changed_at"], unique=False
    )
    op.create_index(
        op.f("ix_account_manager_history_current_mcc_id"), "account_manager_history", ["current_mcc_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_manager_history_previous_mcc_id"), "account_manager_history", ["previous_mcc_id"], unique=False
    )
    op.create_table(
        "control_center_assets",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("resource_name", sa.String(length=255), nullable=False),
        sa.Column("asset_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("asset_type", sa.String(length=80), nullable=True),
        sa.Column("source", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=60), nullable=True),
        sa.Column("policy_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("youtube_video_id", sa.String(length=32), nullable=True),
        sa.Column("youtube_video_title", sa.String(length=255), nullable=True),
        sa.Column("youtube_processing_status", sa.String(length=60), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "resource_name", name="uq_control_center_asset_resource"),
    )
    op.create_index(op.f("ix_control_center_assets_account_id"), "control_center_assets", ["account_id"], unique=False)
    op.create_index(op.f("ix_control_center_assets_asset_id"), "control_center_assets", ["asset_id"], unique=False)
    op.create_index(op.f("ix_control_center_assets_asset_type"), "control_center_assets", ["asset_type"], unique=False)
    op.create_index(op.f("ix_control_center_assets_status"), "control_center_assets", ["status"], unique=False)
    op.create_index(
        op.f("ix_control_center_assets_youtube_video_id"), "control_center_assets", ["youtube_video_id"], unique=False
    )
    op.create_table(
        "conversion_action_mappings",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("scope_key", sa.String(length=80), nullable=False),
        sa.Column("semantic_type", sa.String(length=24), nullable=False),
        sa.Column("resource_name", sa.String(length=255), nullable=False),
        sa.Column("conversion_action_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("owner_customer_id", sa.String(length=32), nullable=True),
        sa.Column("is_cross_account", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["connection_id"], ["google_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_key", "semantic_type", "resource_name", name="uq_conversion_action_mapping"),
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_account_id"), "conversion_action_mappings", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_connection_id"),
        "conversion_action_mappings",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_conversion_action_id"),
        "conversion_action_mappings",
        ["conversion_action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_is_active"), "conversion_action_mappings", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_owner_customer_id"),
        "conversion_action_mappings",
        ["owner_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_scope_key"), "conversion_action_mappings", ["scope_key"], unique=False
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_scope_type"), "conversion_action_mappings", ["scope_type"], unique=False
    )
    op.create_index(
        op.f("ix_conversion_action_mappings_semantic_type"),
        "conversion_action_mappings",
        ["semantic_type"],
        unique=False,
    )
    op.create_table(
        "google_account_access_paths",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("target_customer_id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("mcc_account_id", sa.Uuid(), nullable=True),
        sa.Column("root_customer_id", sa.String(length=32), nullable=False),
        sa.Column("manager_customer_id", sa.String(length=32), nullable=True),
        sa.Column("customer_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("path_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lost_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_request_id", sa.String(length=180), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["connection_id"], ["google_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mcc_account_id"], ["mcc_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id", "target_customer_id", "path_fingerprint", name="uq_google_account_access_path"
        ),
    )
    op.create_index(
        op.f("ix_google_account_access_paths_account_id"), "google_account_access_paths", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_google_account_access_paths_connection_id"),
        "google_account_access_paths",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_first_seen_at"),
        "google_account_access_paths",
        ["first_seen_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_is_active"), "google_account_access_paths", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_google_account_access_paths_is_primary"), "google_account_access_paths", ["is_primary"], unique=False
    )
    op.create_index(
        op.f("ix_google_account_access_paths_last_seen_at"),
        "google_account_access_paths",
        ["last_seen_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_manager_customer_id"),
        "google_account_access_paths",
        ["manager_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_mcc_account_id"),
        "google_account_access_paths",
        ["mcc_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_path_fingerprint"),
        "google_account_access_paths",
        ["path_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_root_customer_id"),
        "google_account_access_paths",
        ["root_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_account_access_paths_target_customer_id"),
        "google_account_access_paths",
        ["target_customer_id"],
        unique=False,
    )
    op.create_table(
        "control_center_ad_groups",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("resource_name", sa.String(length=255), nullable=False),
        sa.Column("ad_group_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("ad_group_type", sa.String(length=80), nullable=True),
        sa.Column("optimized_targeting_enabled", sa.Boolean(), nullable=True),
        sa.Column("impressions", sa.BigInteger(), nullable=True),
        sa.Column("clicks", sa.BigInteger(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("conversions", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("conversion_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("policy_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["campaign_id"], ["control_center_campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "resource_name", name="uq_control_center_ad_group_resource"),
    )
    op.create_index(
        op.f("ix_control_center_ad_groups_account_id"), "control_center_ad_groups", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_ad_groups_ad_group_id"), "control_center_ad_groups", ["ad_group_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_ad_groups_campaign_id"), "control_center_ad_groups", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_control_center_ad_groups_name"), "control_center_ad_groups", ["name"], unique=False)
    op.create_index(op.f("ix_control_center_ad_groups_status"), "control_center_ad_groups", ["status"], unique=False)
    op.create_table(
        "control_center_google_changes",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("event_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("change_resource_name", sa.String(length=512), nullable=True),
        sa.Column("changed_resource_name", sa.String(length=512), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("change_type", sa.String(length=40), nullable=False),
        sa.Column("client_type", sa.String(length=60), nullable=True),
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column("old_resource", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_resource", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=180), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["campaign_id"], ["control_center_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["connection_id"], ["google_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_fingerprint", name="uq_control_center_google_change"),
    )
    op.create_index(
        op.f("ix_control_center_google_changes_account_id"),
        "control_center_google_changes",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_campaign_id"),
        "control_center_google_changes",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_change_type"),
        "control_center_google_changes",
        ["change_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_changed_at"),
        "control_center_google_changes",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_changed_resource_name"),
        "control_center_google_changes",
        ["changed_resource_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_connection_id"),
        "control_center_google_changes",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_event_fingerprint"),
        "control_center_google_changes",
        ["event_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_google_changes_resource_type"),
        "control_center_google_changes",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "control_center_ads",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("ad_group_id", sa.Uuid(), nullable=False),
        sa.Column("resource_name", sa.String(length=255), nullable=False),
        sa.Column("ad_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("ad_type", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("primary_status", sa.String(length=60), nullable=True),
        sa.Column("policy_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("disapproval_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=True),
        sa.Column("clicks", sa.BigInteger(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("conversions", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("conversion_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ad_group_id"], ["control_center_ad_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["campaign_id"], ["control_center_campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "resource_name", name="uq_control_center_ad_resource"),
    )
    op.create_index(op.f("ix_control_center_ads_account_id"), "control_center_ads", ["account_id"], unique=False)
    op.create_index(op.f("ix_control_center_ads_ad_group_id"), "control_center_ads", ["ad_group_id"], unique=False)
    op.create_index(op.f("ix_control_center_ads_ad_id"), "control_center_ads", ["ad_id"], unique=False)
    op.create_index(op.f("ix_control_center_ads_ad_type"), "control_center_ads", ["ad_type"], unique=False)
    op.create_index(op.f("ix_control_center_ads_campaign_id"), "control_center_ads", ["campaign_id"], unique=False)
    op.create_index(
        op.f("ix_control_center_ads_primary_status"), "control_center_ads", ["primary_status"], unique=False
    )
    op.create_index(op.f("ix_control_center_ads_status"), "control_center_ads", ["status"], unique=False)
    op.create_table(
        "control_center_ad_asset_links",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("ad_group_id", sa.Uuid(), nullable=False),
        sa.Column("ad_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("field_type", sa.String(length=80), nullable=False),
        sa.Column("performance_label", sa.String(length=40), nullable=True),
        sa.Column("policy_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["customer_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ad_group_id"], ["control_center_ad_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ad_id"], ["control_center_ads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["control_center_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["campaign_id"], ["control_center_campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ad_id", "asset_id", "field_type", name="uq_control_center_ad_asset_link"),
    )
    op.create_index(
        op.f("ix_control_center_ad_asset_links_account_id"),
        "control_center_ad_asset_links",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_ad_asset_links_ad_group_id"),
        "control_center_ad_asset_links",
        ["ad_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_ad_asset_links_ad_id"), "control_center_ad_asset_links", ["ad_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_ad_asset_links_asset_id"), "control_center_ad_asset_links", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_ad_asset_links_campaign_id"),
        "control_center_ad_asset_links",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_ad_asset_links_field_type"),
        "control_center_ad_asset_links",
        ["field_type"],
        unique=False,
    )
    op.add_column(
        "account_metric_daily", sa.Column("all_conversions", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column("account_metric_daily", sa.Column("registrations", sa.Numeric(precision=24, scale=6), nullable=True))
    op.add_column("account_metric_daily", sa.Column("deposits", sa.Numeric(precision=24, scale=6), nullable=True))
    op.add_column(
        "account_metric_daily", sa.Column("registration_value", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column("account_metric_daily", sa.Column("deposit_value", sa.Numeric(precision=24, scale=6), nullable=True))
    op.add_column(
        "account_metric_daily",
        sa.Column("registration_data_available", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "account_metric_daily",
        sa.Column("deposit_data_available", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("account_metric_daily", sa.Column("budget_micros", sa.BigInteger(), nullable=True))
    op.add_column("account_metric_daily", sa.Column("active_campaigns", sa.Integer(), nullable=True))
    op.add_column("account_metric_daily", sa.Column("disapproved_ads", sa.Integer(), nullable=True))
    op.add_column("account_metric_daily", sa.Column("request_id", sa.String(length=180), nullable=True))
    op.add_column(
        "account_monitoring_states", sa.Column("all_conversions", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column(
        "account_monitoring_states", sa.Column("registrations", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column("account_monitoring_states", sa.Column("deposits", sa.Numeric(precision=24, scale=6), nullable=True))
    op.add_column(
        "account_monitoring_states", sa.Column("registration_value", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column(
        "account_monitoring_states", sa.Column("deposit_value", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column(
        "account_monitoring_states",
        sa.Column("registration_data_available", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "account_monitoring_states",
        sa.Column("deposit_data_available", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("account_monitoring_states", sa.Column("budget_micros", sa.BigInteger(), nullable=True))
    op.add_column("account_monitoring_states", sa.Column("disapproved_ads", sa.Integer(), nullable=True))
    op.add_column("control_center_campaigns", sa.Column("bidding_strategy_type", sa.String(length=80), nullable=True))
    op.add_column(
        "control_center_campaigns", sa.Column("all_conversions", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column(
        "control_center_campaigns", sa.Column("registrations", sa.Numeric(precision=24, scale=6), nullable=True)
    )
    op.add_column("control_center_campaigns", sa.Column("deposits", sa.Numeric(precision=24, scale=6), nullable=True))
    op.add_column(
        "control_center_campaigns",
        sa.Column("registration_data_available", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "control_center_campaigns",
        sa.Column("deposit_data_available", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("control_center_campaigns", sa.Column("policy_status", sa.String(length=60), nullable=True))
    op.add_column("control_center_campaigns", sa.Column("last_change_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_control_center_campaigns_policy_status"), "control_center_campaigns", ["policy_status"], unique=False
    )
    op.add_column("control_center_problems", sa.Column("resource_name", sa.String(length=512), nullable=True))
    op.add_column("control_center_problems", sa.Column("google_message", sa.Text(), nullable=True))
    op.add_column("control_center_problems", sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "control_center_problems",
        sa.Column(
            "previous_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "control_center_problems",
        sa.Column(
            "current_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_control_center_problems_resource_name"), "control_center_problems", ["resource_name"], unique=False
    )
    op.add_column("control_center_rule_evaluations", sa.Column("skip_reason", sa.String(length=120), nullable=True))
    op.add_column("control_center_rule_evaluations", sa.Column("idempotency_key", sa.String(length=180), nullable=True))
    op.add_column("control_center_rule_evaluations", sa.Column("action_request_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_control_center_rule_evaluations_action_request_id"),
        "control_center_rule_evaluations",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_rule_evaluations_skip_reason"),
        "control_center_rule_evaluations",
        ["skip_reason"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_rule_evaluation_idempotency", "control_center_rule_evaluations", ["idempotency_key"]
    )
    op.create_foreign_key(
        "fk_rule_evaluation_action_request",
        "control_center_rule_evaluations",
        "control_center_action_requests",
        ["action_request_id"],
        ["id"],
    )
    op.add_column("control_center_rules", sa.Column("priority", sa.Integer(), server_default="100", nullable=False))
    op.add_column(
        "control_center_rules",
        sa.Column(
            "schedule", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column(
        "control_center_rules", sa.Column("max_budget_change_percent", sa.Numeric(precision=8, scale=3), nullable=True)
    )
    op.add_column("control_center_rules", sa.Column("live_confirmed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("control_center_rules", sa.Column("live_confirmed_by_id", sa.Uuid(), nullable=True))
    op.add_column("control_center_rules", sa.Column("last_action_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_control_center_rules_priority"), "control_center_rules", ["priority"], unique=False)
    op.create_foreign_key(
        "fk_control_center_rules_live_confirmed_by", "control_center_rules", "users", ["live_confirmed_by_id"], ["id"]
    )
    op.add_column(
        "control_center_saved_views", sa.Column("is_shared", sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    op.add_column("control_center_saved_views", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("control_center_saved_views", sa.Column("source_view_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_control_center_saved_views_is_shared"), "control_center_saved_views", ["is_shared"], unique=False
    )
    op.create_foreign_key(
        "fk_saved_view_source", "control_center_saved_views", "control_center_saved_views", ["source_view_id"], ["id"]
    )
    op.add_column(
        "control_center_sync_items",
        sa.Column(
            "cursor_before",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "control_center_sync_items",
        sa.Column(
            "cursor_after",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("control_center_sync_items", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "control_center_sync_runs",
        sa.Column(
            "cursor", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column(
        "control_center_sync_runs",
        sa.Column(
            "request_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "control_center_sync_runs",
        sa.Column(
            "statistics", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column("control_center_sync_runs", sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("control_center_sync_runs", sa.Column("duration_ms", sa.Integer(), nullable=True))
    op.add_column("customer_accounts", sa.Column("primary_mcc_id", sa.Uuid(), nullable=True))
    op.add_column("customer_accounts", sa.Column("geo_id", sa.Uuid(), nullable=True))
    op.add_column("customer_accounts", sa.Column("geo_override_id", sa.Uuid(), nullable=True))
    op.add_column("customer_accounts", sa.Column("geo_override_by_id", sa.Uuid(), nullable=True))
    op.add_column("customer_accounts", sa.Column("geo_override_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "customer_accounts",
        sa.Column("activity_status", sa.String(length=40), server_default="NO_DATA", nullable=False),
    )
    op.add_column(
        "customer_accounts", sa.Column("activity_period_days", sa.Integer(), server_default="7", nullable=False)
    )
    op.add_column("customer_accounts", sa.Column("next_sync_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "customer_accounts", sa.Column("sync_interval_minutes", sa.Integer(), server_default="360", nullable=False)
    )
    op.create_index(
        op.f("ix_customer_accounts_activity_status"), "customer_accounts", ["activity_status"], unique=False
    )
    op.create_index(op.f("ix_customer_accounts_geo_id"), "customer_accounts", ["geo_id"], unique=False)
    op.create_index(
        op.f("ix_customer_accounts_geo_override_id"), "customer_accounts", ["geo_override_id"], unique=False
    )
    op.create_index(op.f("ix_customer_accounts_next_sync_at"), "customer_accounts", ["next_sync_at"], unique=False)
    op.create_index(op.f("ix_customer_accounts_primary_mcc_id"), "customer_accounts", ["primary_mcc_id"], unique=False)
    op.create_foreign_key(
        "fk_customer_accounts_primary_mcc", "customer_accounts", "mcc_accounts", ["primary_mcc_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_customer_accounts_geo_override_by", "customer_accounts", "users", ["geo_override_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_customer_accounts_geo_override", "customer_accounts", "geo_definitions", ["geo_override_id"], ["id"]
    )
    op.create_foreign_key("fk_customer_accounts_geo", "customer_accounts", "geo_definitions", ["geo_id"], ["id"])
    op.add_column("mcc_accounts", sa.Column("parent_customer_id", sa.String(length=32), nullable=True))
    op.add_column("mcc_accounts", sa.Column("is_root", sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column("mcc_accounts", sa.Column("hierarchy_level", sa.Integer(), nullable=True))
    op.add_column("mcc_accounts", sa.Column("geo_id", sa.Uuid(), nullable=True))
    op.add_column("mcc_accounts", sa.Column("geo_assigned_by_id", sa.Uuid(), nullable=True))
    op.add_column("mcc_accounts", sa.Column("geo_assigned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("mcc_accounts", sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("mcc_accounts", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("mcc_accounts", sa.Column("detached_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_mcc_accounts_detached_at"), "mcc_accounts", ["detached_at"], unique=False)
    op.create_index(op.f("ix_mcc_accounts_geo_id"), "mcc_accounts", ["geo_id"], unique=False)
    op.create_index(op.f("ix_mcc_accounts_is_root"), "mcc_accounts", ["is_root"], unique=False)
    op.create_index(op.f("ix_mcc_accounts_last_seen_at"), "mcc_accounts", ["last_seen_at"], unique=False)
    op.create_index(op.f("ix_mcc_accounts_parent_customer_id"), "mcc_accounts", ["parent_customer_id"], unique=False)
    op.create_foreign_key("fk_mcc_accounts_geo_assigned_by", "mcc_accounts", "users", ["geo_assigned_by_id"], ["id"])
    op.create_foreign_key("fk_mcc_accounts_geo", "mcc_accounts", "geo_definitions", ["geo_id"], ["id"])
    op.add_column("users", sa.Column("time_zone", sa.String(length=80), server_default="Europe/Moscow", nullable=False))
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.execute(
        """
        UPDATE mcc_accounts AS m
        SET
            is_root = (m.customer_id = g.login_customer_id),
            first_seen_at = COALESCE(m.first_seen_at, m.created_at),
            last_seen_at = COALESCE(m.last_seen_at, m.last_sync_success_at, m.updated_at)
        FROM google_connections AS g
        WHERE g.id = m.connection_id
        """
    )
    op.execute(
        """
        UPDATE customer_accounts AS account
        SET primary_mcc_id = mcc.id
        FROM mcc_accounts AS mcc
        WHERE
            account.connection_id = mcc.connection_id
            AND account.manager_customer_id = mcc.customer_id
            AND account.primary_mcc_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError(
        "Migration 202607300008 is intentionally additive and cannot be downgraded "
        "without an explicit data-preserving migration."
    )
