"""add google ads control center

Revision ID: fabc2ba828ea
Revises: 202607260006
Create Date: 2026-07-27 15:58:53.387866
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "fabc2ba828ea"
down_revision = "202607260006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_center_rules",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("condition_logic", sa.String(length=10), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("safeguards", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("max_actions_per_run", sa.Integer(), nullable=False),
        sa.Column("max_actions_per_day", sa.Integer(), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("circuit_open_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_control_center_rules_created_by_id"), "control_center_rules", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_control_center_rules_enabled"), "control_center_rules", ["enabled"], unique=False)
    op.create_index(op.f("ix_control_center_rules_mode"), "control_center_rules", ["mode"], unique=False)
    op.create_table(
        "control_center_saved_views",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("entity_level", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "entity_level", "name", name="uq_control_center_saved_view"),
    )
    op.create_index(
        op.f("ix_control_center_saved_views_entity_level"), "control_center_saved_views", ["entity_level"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_saved_views_is_default"), "control_center_saved_views", ["is_default"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_saved_views_owner_user_id"),
        "control_center_saved_views",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "control_center_tags",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_control_center_tags_name"), "control_center_tags", ["name"], unique=True)
    op.create_table(
        "control_center_quota_ledger",
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("operation_count", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("request_id", sa.String(length=180), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["google_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_center_quota_ledger_category"), "control_center_quota_ledger", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_quota_ledger_connection_id"),
        "control_center_quota_ledger",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_quota_ledger_operation_date"),
        "control_center_quota_ledger",
        ["operation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_quota_ledger_succeeded"), "control_center_quota_ledger", ["succeeded"], unique=False
    )
    op.create_table(
        "account_metric_daily",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("timezone_mode", sa.String(length=30), nullable=False),
        sa.Column("boundary_precision", sa.String(length=30), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=True),
        sa.Column("clicks", sa.BigInteger(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("conversions", sa.Float(), nullable=True),
        sa.Column("conversion_value", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "metric_date", "timezone_mode", name="uq_account_metric_daily"),
    )
    op.create_index(op.f("ix_account_metric_daily_account_id"), "account_metric_daily", ["account_id"], unique=False)
    op.create_index(op.f("ix_account_metric_daily_metric_date"), "account_metric_daily", ["metric_date"], unique=False)
    op.create_table(
        "account_monitoring_states",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone_mode", sa.String(length=30), nullable=False),
        sa.Column("boundary_precision", sa.String(length=30), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=True),
        sa.Column("clicks", sa.BigInteger(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("conversions", sa.Float(), nullable=True),
        sa.Column("conversion_value", sa.Float(), nullable=True),
        sa.Column("active_campaigns", sa.Integer(), nullable=True),
        sa.Column("policy_issues", sa.Integer(), nullable=True),
        sa.Column("freshness", sa.String(length=30), nullable=False),
        sa.Column("data_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aggregated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=120), nullable=True),
        sa.Column("last_request_id", sa.String(length=180), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_monitoring_states_account_id"), "account_monitoring_states", ["account_id"], unique=True
    )
    op.create_index(
        op.f("ix_account_monitoring_states_freshness"), "account_monitoring_states", ["freshness"], unique=False
    )
    op.create_table(
        "account_note_history",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("previous_note", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("changed_by_id", sa.Uuid(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_note_history_account_id"), "account_note_history", ["account_id"], unique=False)
    op.create_index(op.f("ix_account_note_history_changed_at"), "account_note_history", ["changed_at"], unique=False)
    op.create_table(
        "account_tag_history",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("tag_name", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("changed_by_id", sa.Uuid(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_tag_history_account_id"), "account_tag_history", ["account_id"], unique=False)
    op.create_index(op.f("ix_account_tag_history_action"), "account_tag_history", ["action"], unique=False)
    op.create_index(op.f("ix_account_tag_history_changed_at"), "account_tag_history", ["changed_at"], unique=False)
    op.create_index(op.f("ix_account_tag_history_tag_name"), "account_tag_history", ["tag_name"], unique=False)
    op.create_table(
        "account_tags",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["control_center_tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "tag_id", name="uq_account_tag"),
    )
    op.create_index(op.f("ix_account_tags_account_id"), "account_tags", ["account_id"], unique=False)
    op.create_index(op.f("ix_account_tags_assigned_at"), "account_tags", ["assigned_at"], unique=False)
    op.create_index(op.f("ix_account_tags_tag_id"), "account_tags", ["tag_id"], unique=False)
    op.create_table(
        "control_center_sync_runs",
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("estimated_operations", sa.Integer(), nullable=False),
        sa.Column("actual_operations", sa.Integer(), nullable=False),
        sa.Column("successful_accounts", sa.Integer(), nullable=False),
        sa.Column("failed_accounts", sa.Integer(), nullable=False),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["google_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_center_sync_runs_connection_id"), "control_center_sync_runs", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_sync_runs_idempotency_key"),
        "control_center_sync_runs",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(op.f("ix_control_center_sync_runs_job_id"), "control_center_sync_runs", ["job_id"], unique=False)
    op.create_index(op.f("ix_control_center_sync_runs_scope"), "control_center_sync_runs", ["scope"], unique=False)
    op.create_index(op.f("ix_control_center_sync_runs_status"), "control_center_sync_runs", ["status"], unique=False)
    op.create_table(
        "control_center_sync_items",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("operations", sa.Integer(), nullable=False),
        sa.Column("request_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=160), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["control_center_sync_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sync_run_id", "account_id", name="uq_control_center_sync_item"),
    )
    op.create_index(
        op.f("ix_control_center_sync_items_account_id"), "control_center_sync_items", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_control_center_sync_items_status"), "control_center_sync_items", ["status"], unique=False)
    op.create_index(
        op.f("ix_control_center_sync_items_sync_run_id"), "control_center_sync_items", ["sync_run_id"], unique=False
    )
    op.create_table(
        "control_center_campaigns",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("uploader_campaign_instance_id", sa.Uuid(), nullable=True),
        sa.Column("resource_name", sa.String(length=255), nullable=False),
        sa.Column("campaign_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("channel_type", sa.String(length=60), nullable=True),
        sa.Column("channel_subtype", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("primary_status", sa.String(length=60), nullable=True),
        sa.Column("primary_status_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget_resource_name", sa.String(length=255), nullable=True),
        sa.Column("budget_micros", sa.BigInteger(), nullable=True),
        sa.Column("budget_shared", sa.Boolean(), nullable=True),
        sa.Column("impressions", sa.BigInteger(), nullable=True),
        sa.Column("clicks", sa.BigInteger(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("conversions", sa.Float(), nullable=True),
        sa.Column("conversion_value", sa.Float(), nullable=True),
        sa.Column("policy_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manually_paused", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["google_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploader_campaign_instance_id"],
            ["campaign_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "resource_name", name="uq_control_center_campaign_resource"),
    )
    op.create_index(
        op.f("ix_control_center_campaigns_account_id"), "control_center_campaigns", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_campaigns_campaign_id"), "control_center_campaigns", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_campaigns_channel_type"), "control_center_campaigns", ["channel_type"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_campaigns_connection_id"), "control_center_campaigns", ["connection_id"], unique=False
    )
    op.create_index(op.f("ix_control_center_campaigns_name"), "control_center_campaigns", ["name"], unique=False)
    op.create_index(
        op.f("ix_control_center_campaigns_primary_status"), "control_center_campaigns", ["primary_status"], unique=False
    )
    op.create_index(op.f("ix_control_center_campaigns_source"), "control_center_campaigns", ["source"], unique=False)
    op.create_index(op.f("ix_control_center_campaigns_status"), "control_center_campaigns", ["status"], unique=False)
    op.create_index(
        op.f("ix_control_center_campaigns_uploader_campaign_instance_id"),
        "control_center_campaigns",
        ["uploader_campaign_instance_id"],
        unique=False,
    )
    op.create_table(
        "control_center_action_requests",
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column("execution_mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pre_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preview", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("readback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmation_token_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmation_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("request_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["control_center_campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_center_action_requests_account_id"),
        "control_center_action_requests",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_action_requests_action_type"),
        "control_center_action_requests",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_action_requests_campaign_id"),
        "control_center_action_requests",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_action_requests_execution_mode"),
        "control_center_action_requests",
        ["execution_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_action_requests_idempotency_key"),
        "control_center_action_requests",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_control_center_action_requests_requested_by_id"),
        "control_center_action_requests",
        ["requested_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_action_requests_status"), "control_center_action_requests", ["status"], unique=False
    )
    op.create_table(
        "control_center_events",
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["control_center_campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_control_center_events_account_id"), "control_center_events", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_control_center_events_campaign_id"), "control_center_events", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_control_center_events_event_type"), "control_center_events", ["event_type"], unique=False)
    op.create_index(
        op.f("ix_control_center_events_occurred_at"), "control_center_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_control_center_events_source"), "control_center_events", ["source"], unique=False)
    op.create_table(
        "control_center_problems",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("problem_type", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("google_code", sa.String(length=160), nullable=True),
        sa.Column("request_id", sa.String(length=180), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["control_center_campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["google_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_control_center_problem_fingerprint"),
    )
    op.create_index(
        op.f("ix_control_center_problems_account_id"), "control_center_problems", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_problems_campaign_id"), "control_center_problems", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_problems_connection_id"), "control_center_problems", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_problems_fingerprint"), "control_center_problems", ["fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_problems_first_seen_at"), "control_center_problems", ["first_seen_at"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_problems_last_seen_at"), "control_center_problems", ["last_seen_at"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_problems_problem_type"), "control_center_problems", ["problem_type"], unique=False
    )
    op.create_index(op.f("ix_control_center_problems_severity"), "control_center_problems", ["severity"], unique=False)
    op.create_index(op.f("ix_control_center_problems_state"), "control_center_problems", ["state"], unique=False)
    op.create_table(
        "control_center_rule_evaluations",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mutation_performed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["control_center_campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["control_center_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_center_rule_evaluations_account_id"),
        "control_center_rule_evaluations",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_rule_evaluations_campaign_id"),
        "control_center_rule_evaluations",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_rule_evaluations_matched"), "control_center_rule_evaluations", ["matched"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_rule_evaluations_rule_id"), "control_center_rule_evaluations", ["rule_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_rule_evaluations_status"), "control_center_rule_evaluations", ["status"], unique=False
    )
    op.create_table(
        "control_center_action_items",
        sa.Column("action_request_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_id", sa.String(length=180), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customer_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["control_center_action_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["control_center_campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_center_action_items_account_id"), "control_center_action_items", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_action_items_action_request_id"),
        "control_center_action_items",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_center_action_items_campaign_id"), "control_center_action_items", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_control_center_action_items_status"), "control_center_action_items", ["status"], unique=False
    )
    op.add_column("customer_accounts", sa.Column("parent_customer_id", sa.String(length=32), nullable=True))
    op.add_column("customer_accounts", sa.Column("hierarchy_level", sa.Integer(), nullable=True))
    op.add_column("customer_accounts", sa.Column("link_status", sa.String(length=40), nullable=True))
    op.add_column("customer_accounts", sa.Column("local_name", sa.String(length=255), nullable=True))
    op.add_column(
        "customer_accounts",
        sa.Column(
            "work_status",
            sa.String(length=40),
            server_default="UNCLASSIFIED",
            nullable=False,
        ),
    )
    op.add_column("customer_accounts", sa.Column("current_note", sa.Text(), nullable=True))
    op.add_column("customer_accounts", sa.Column("note_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("note_updated_by_id", sa.Uuid(), nullable=True))
    op.add_column(
        "customer_accounts",
        sa.Column("is_pinned", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("customer_accounts", sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("detached_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("last_sync_attempt_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("last_sync_success_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("sync_error", sa.Text(), nullable=True))
    op.add_column("customer_accounts", sa.Column("verification_status", sa.String(length=60), nullable=True))
    op.add_column("customer_accounts", sa.Column("verification_deadline", sa.DateTime(timezone=True), nullable=True))
    op.add_column("customer_accounts", sa.Column("verification_action_url", sa.Text(), nullable=True))
    op.add_column("customer_accounts", sa.Column("verification_checked_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_customer_accounts_detached_at"), "customer_accounts", ["detached_at"], unique=False)
    op.create_index(op.f("ix_customer_accounts_is_pinned"), "customer_accounts", ["is_pinned"], unique=False)
    op.create_index(op.f("ix_customer_accounts_link_status"), "customer_accounts", ["link_status"], unique=False)
    op.create_index(op.f("ix_customer_accounts_local_name"), "customer_accounts", ["local_name"], unique=False)
    op.create_index(
        op.f("ix_customer_accounts_parent_customer_id"), "customer_accounts", ["parent_customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_accounts_verification_status"), "customer_accounts", ["verification_status"], unique=False
    )
    op.create_index(op.f("ix_customer_accounts_work_status"), "customer_accounts", ["work_status"], unique=False)
    op.create_foreign_key(None, "customer_accounts", "users", ["note_updated_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "customer_accounts", type_="foreignkey")
    op.drop_index(op.f("ix_customer_accounts_work_status"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_verification_status"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_parent_customer_id"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_local_name"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_link_status"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_is_pinned"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_detached_at"), table_name="customer_accounts")
    op.drop_column("customer_accounts", "verification_checked_at")
    op.drop_column("customer_accounts", "verification_action_url")
    op.drop_column("customer_accounts", "verification_deadline")
    op.drop_column("customer_accounts", "verification_status")
    op.drop_column("customer_accounts", "sync_error")
    op.drop_column("customer_accounts", "last_sync_success_at")
    op.drop_column("customer_accounts", "last_sync_attempt_at")
    op.drop_column("customer_accounts", "detached_at")
    op.drop_column("customer_accounts", "last_seen_at")
    op.drop_column("customer_accounts", "first_seen_at")
    op.drop_column("customer_accounts", "is_pinned")
    op.drop_column("customer_accounts", "note_updated_by_id")
    op.drop_column("customer_accounts", "note_updated_at")
    op.drop_column("customer_accounts", "current_note")
    op.drop_column("customer_accounts", "work_status")
    op.drop_column("customer_accounts", "local_name")
    op.drop_column("customer_accounts", "link_status")
    op.drop_column("customer_accounts", "hierarchy_level")
    op.drop_column("customer_accounts", "parent_customer_id")
    op.drop_index(op.f("ix_control_center_action_items_status"), table_name="control_center_action_items")
    op.drop_index(op.f("ix_control_center_action_items_campaign_id"), table_name="control_center_action_items")
    op.drop_index(op.f("ix_control_center_action_items_action_request_id"), table_name="control_center_action_items")
    op.drop_index(op.f("ix_control_center_action_items_account_id"), table_name="control_center_action_items")
    op.drop_table("control_center_action_items")
    op.drop_index(op.f("ix_control_center_rule_evaluations_status"), table_name="control_center_rule_evaluations")
    op.drop_index(op.f("ix_control_center_rule_evaluations_rule_id"), table_name="control_center_rule_evaluations")
    op.drop_index(op.f("ix_control_center_rule_evaluations_matched"), table_name="control_center_rule_evaluations")
    op.drop_index(op.f("ix_control_center_rule_evaluations_campaign_id"), table_name="control_center_rule_evaluations")
    op.drop_index(op.f("ix_control_center_rule_evaluations_account_id"), table_name="control_center_rule_evaluations")
    op.drop_table("control_center_rule_evaluations")
    op.drop_index(op.f("ix_control_center_problems_state"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_severity"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_problem_type"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_last_seen_at"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_first_seen_at"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_fingerprint"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_connection_id"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_campaign_id"), table_name="control_center_problems")
    op.drop_index(op.f("ix_control_center_problems_account_id"), table_name="control_center_problems")
    op.drop_table("control_center_problems")
    op.drop_index(op.f("ix_control_center_events_source"), table_name="control_center_events")
    op.drop_index(op.f("ix_control_center_events_occurred_at"), table_name="control_center_events")
    op.drop_index(op.f("ix_control_center_events_event_type"), table_name="control_center_events")
    op.drop_index(op.f("ix_control_center_events_campaign_id"), table_name="control_center_events")
    op.drop_index(op.f("ix_control_center_events_account_id"), table_name="control_center_events")
    op.drop_table("control_center_events")
    op.drop_index(op.f("ix_control_center_action_requests_status"), table_name="control_center_action_requests")
    op.drop_index(
        op.f("ix_control_center_action_requests_requested_by_id"), table_name="control_center_action_requests"
    )
    op.drop_index(
        op.f("ix_control_center_action_requests_idempotency_key"), table_name="control_center_action_requests"
    )
    op.drop_index(op.f("ix_control_center_action_requests_execution_mode"), table_name="control_center_action_requests")
    op.drop_index(op.f("ix_control_center_action_requests_campaign_id"), table_name="control_center_action_requests")
    op.drop_index(op.f("ix_control_center_action_requests_action_type"), table_name="control_center_action_requests")
    op.drop_index(op.f("ix_control_center_action_requests_account_id"), table_name="control_center_action_requests")
    op.drop_table("control_center_action_requests")
    op.drop_index(
        op.f("ix_control_center_campaigns_uploader_campaign_instance_id"), table_name="control_center_campaigns"
    )
    op.drop_index(op.f("ix_control_center_campaigns_status"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_source"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_primary_status"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_name"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_connection_id"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_channel_type"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_campaign_id"), table_name="control_center_campaigns")
    op.drop_index(op.f("ix_control_center_campaigns_account_id"), table_name="control_center_campaigns")
    op.drop_table("control_center_campaigns")
    op.drop_index(op.f("ix_control_center_sync_items_sync_run_id"), table_name="control_center_sync_items")
    op.drop_index(op.f("ix_control_center_sync_items_status"), table_name="control_center_sync_items")
    op.drop_index(op.f("ix_control_center_sync_items_account_id"), table_name="control_center_sync_items")
    op.drop_table("control_center_sync_items")
    op.drop_index(op.f("ix_control_center_sync_runs_status"), table_name="control_center_sync_runs")
    op.drop_index(op.f("ix_control_center_sync_runs_scope"), table_name="control_center_sync_runs")
    op.drop_index(op.f("ix_control_center_sync_runs_job_id"), table_name="control_center_sync_runs")
    op.drop_index(op.f("ix_control_center_sync_runs_idempotency_key"), table_name="control_center_sync_runs")
    op.drop_index(op.f("ix_control_center_sync_runs_connection_id"), table_name="control_center_sync_runs")
    op.drop_table("control_center_sync_runs")
    op.drop_index(op.f("ix_account_tags_tag_id"), table_name="account_tags")
    op.drop_index(op.f("ix_account_tags_assigned_at"), table_name="account_tags")
    op.drop_index(op.f("ix_account_tags_account_id"), table_name="account_tags")
    op.drop_table("account_tags")
    op.drop_index(op.f("ix_account_tag_history_tag_name"), table_name="account_tag_history")
    op.drop_index(op.f("ix_account_tag_history_changed_at"), table_name="account_tag_history")
    op.drop_index(op.f("ix_account_tag_history_action"), table_name="account_tag_history")
    op.drop_index(op.f("ix_account_tag_history_account_id"), table_name="account_tag_history")
    op.drop_table("account_tag_history")
    op.drop_index(op.f("ix_account_note_history_changed_at"), table_name="account_note_history")
    op.drop_index(op.f("ix_account_note_history_account_id"), table_name="account_note_history")
    op.drop_table("account_note_history")
    op.drop_index(op.f("ix_account_monitoring_states_freshness"), table_name="account_monitoring_states")
    op.drop_index(op.f("ix_account_monitoring_states_account_id"), table_name="account_monitoring_states")
    op.drop_table("account_monitoring_states")
    op.drop_index(op.f("ix_account_metric_daily_metric_date"), table_name="account_metric_daily")
    op.drop_index(op.f("ix_account_metric_daily_account_id"), table_name="account_metric_daily")
    op.drop_table("account_metric_daily")
    op.drop_index(op.f("ix_control_center_quota_ledger_succeeded"), table_name="control_center_quota_ledger")
    op.drop_index(op.f("ix_control_center_quota_ledger_operation_date"), table_name="control_center_quota_ledger")
    op.drop_index(op.f("ix_control_center_quota_ledger_connection_id"), table_name="control_center_quota_ledger")
    op.drop_index(op.f("ix_control_center_quota_ledger_category"), table_name="control_center_quota_ledger")
    op.drop_table("control_center_quota_ledger")
    op.drop_index(op.f("ix_control_center_tags_name"), table_name="control_center_tags")
    op.drop_table("control_center_tags")
    op.drop_index(op.f("ix_control_center_saved_views_owner_user_id"), table_name="control_center_saved_views")
    op.drop_index(op.f("ix_control_center_saved_views_is_default"), table_name="control_center_saved_views")
    op.drop_index(op.f("ix_control_center_saved_views_entity_level"), table_name="control_center_saved_views")
    op.drop_table("control_center_saved_views")
    op.drop_index(op.f("ix_control_center_rules_mode"), table_name="control_center_rules")
    op.drop_index(op.f("ix_control_center_rules_enabled"), table_name="control_center_rules")
    op.drop_index(op.f("ix_control_center_rules_created_by_id"), table_name="control_center_rules")
    op.drop_table("control_center_rules")
    # ### end Alembic commands ###
